<?php

declare(strict_types=1);

return [
    'blogs' => [
        'label' => 'Blogs',
        'table' => 'blogs',
        'pk' => 'id',
        'fields' => [
            'title' => ['label' => 'Title', 'type' => 'text', 'required' => true],
            'slug' => ['label' => 'Slug', 'type' => 'text', 'auto_slug_from' => 'title'],
            'short_description' => ['label' => 'Short Description', 'type' => 'textarea'],
            'description' => ['label' => 'Description', 'type' => 'textarea'],
            'featured_image' => ['label' => 'Featured Image', 'type' => 'image'],
            'author' => ['label' => 'Author', 'type' => 'text'],
            'publish_date' => ['label' => 'Publish Date', 'type' => 'date'],
            'meta_title' => ['label' => 'Meta Title', 'type' => 'text'],
            'meta_keywords' => ['label' => 'Meta Keywords', 'type' => 'textarea'],
            'meta_description' => ['label' => 'Meta Description', 'type' => 'textarea'],
            'featured' => ['label' => 'Featured', 'type' => 'checkbox'],
            'status' => ['label' => 'Status', 'type' => 'checkbox'],
        ],
    ],
    'news' => [
        'label' => 'News',
        'table' => 'blogs',
        'pk' => 'id',
        'fields' => [
            'title' => ['label' => 'Title', 'type' => 'text', 'required' => true],
            'slug' => ['label' => 'Slug', 'type' => 'text', 'auto_slug_from' => 'title'],
            'short_description' => ['label' => 'Short Description', 'type' => 'textarea'],
            'description' => ['label' => 'Description', 'type' => 'textarea'],
            'featured_image' => ['label' => 'Featured Image', 'type' => 'image'],
            'author' => ['label' => 'Author', 'type' => 'text'],
            'publish_date' => ['label' => 'Publish Date', 'type' => 'date'],
            'meta_title' => ['label' => 'Meta Title', 'type' => 'text'],
            'meta_keywords' => ['label' => 'Meta Keywords', 'type' => 'textarea'],
            'meta_description' => ['label' => 'Meta Description', 'type' => 'textarea'],
            'featured' => ['label' => 'Featured', 'type' => 'checkbox'],
            'status' => ['label' => 'Status', 'type' => 'checkbox'],
        ],
    ],
    'testimonials' => [
        'label' => 'Testimonials',
        'table' => 'testimonials',
        'pk' => 'id',
        'fields' => [
            'customer_name' => ['label' => 'Customer Name', 'type' => 'text', 'required' => true],
            'company' => ['label' => 'Company', 'type' => 'text'],
            'designation' => ['label' => 'Designation', 'type' => 'text'],
            'photo' => ['label' => 'Photo', 'type' => 'image'],
            'rating' => ['label' => 'Rating', 'type' => 'number'],
            'review' => ['label' => 'Review', 'type' => 'textarea', 'required' => true],
            'featured' => ['label' => 'Featured', 'type' => 'checkbox'],
            'status' => ['label' => 'Status', 'type' => 'checkbox'],
        ],
    ],
    'gallery' => [
        'label' => 'Gallery',
        'table' => 'gallery',
        'pk' => 'id',
        'fields' => [
            'title' => ['label' => 'Title', 'type' => 'text', 'required' => true],
            'category' => ['label' => 'Category', 'type' => 'text'],
            'cover_image' => ['label' => 'Cover Image', 'type' => 'image'],
            'description' => ['label' => 'Description', 'type' => 'textarea'],
            'featured' => ['label' => 'Featured', 'type' => 'checkbox'],
            'status' => ['label' => 'Status', 'type' => 'checkbox'],
        ],
    ],
    'hero-slides' => [
        'label' => 'Hero Slides',
        'table' => 'hero_slides',
        'pk' => 'id',
        'fields' => [
            'title' => ['label' => 'Title', 'type' => 'text', 'required' => true],
            'subtitle' => ['label' => 'Subtitle', 'type' => 'textarea'],
            'button_text' => ['label' => 'Button Text', 'type' => 'text'],
            'button_link' => ['label' => 'Button Link', 'type' => 'text'],
            'image' => ['label' => 'Image', 'type' => 'image'],
            'mobile_image' => ['label' => 'Mobile Image', 'type' => 'image'],
            'sort_order' => ['label' => 'Sort Order', 'type' => 'number'],
            'status' => ['label' => 'Status', 'type' => 'checkbox'],
        ],
    ],
    'services' => [
        'label' => 'Services',
        'table' => 'services',
        'pk' => 'id',
        'fields' => [
            'service_name' => ['label' => 'Service Name', 'type' => 'text', 'required' => true],
            'slug' => ['label' => 'Slug', 'type' => 'text', 'auto_slug_from' => 'service_name'],
            'short_description' => ['label' => 'Short Description', 'type' => 'textarea'],
            'description' => ['label' => 'Description', 'type' => 'textarea'],
            'icon' => ['label' => 'Icon', 'type' => 'text'],
            'image' => ['label' => 'Image', 'type' => 'image'],
            'banner' => ['label' => 'Banner', 'type' => 'image'],
            'meta_title' => ['label' => 'Meta Title', 'type' => 'text'],
            'meta_keywords' => ['label' => 'Meta Keywords', 'type' => 'textarea'],
            'meta_description' => ['label' => 'Meta Description', 'type' => 'textarea'],
            'sort_order' => ['label' => 'Sort Order', 'type' => 'number'],
            'featured' => ['label' => 'Featured', 'type' => 'checkbox'],
            'status' => ['label' => 'Status', 'type' => 'checkbox'],
        ],
    ],
    'projects' => [
        'label' => 'Projects',
        'table' => 'projects',
        'pk' => 'id',
        'fields' => [
            'project_name' => ['label' => 'Project Name', 'type' => 'text', 'required' => true],
            'slug' => ['label' => 'Slug', 'type' => 'text', 'auto_slug_from' => 'project_name'],
            'client_name' => ['label' => 'Client Name', 'type' => 'text'],
            'location' => ['label' => 'Location', 'type' => 'text'],
            'category' => ['label' => 'Category', 'type' => 'text'],
            'capacity' => ['label' => 'Capacity', 'type' => 'text'],
            'completion_date' => ['label' => 'Completion Date', 'type' => 'date'],
            'short_description' => ['label' => 'Short Description', 'type' => 'textarea'],
            'description' => ['label' => 'Description', 'type' => 'textarea'],
            'thumbnail' => ['label' => 'Thumbnail', 'type' => 'image'],
            'banner' => ['label' => 'Banner', 'type' => 'image'],
            'gallery' => ['label' => 'Gallery', 'type' => 'textarea'],
            'featured' => ['label' => 'Featured', 'type' => 'checkbox'],
            'status' => ['label' => 'Status', 'type' => 'checkbox'],
        ],
    ],
    'pages' => [
        'label' => 'Pages',
        'table' => 'pages',
        'pk' => 'id',
        'fields' => [
            'page_name' => ['label' => 'Page Name', 'type' => 'text', 'required' => true],
            'slug' => ['label' => 'Slug', 'type' => 'text', 'auto_slug_from' => 'page_name'],
            'page_title' => ['label' => 'Page Title', 'type' => 'text'],
            'meta_description' => ['label' => 'Meta Description', 'type' => 'textarea'],
            'content' => ['label' => 'Content', 'type' => 'textarea'],
            'status' => ['label' => 'Status', 'type' => 'checkbox'],
        ],
    ],
];