<?php

declare(strict_types=1);

return [
    'company' => [
        'name' => 'HeliWind Energy Solution',
        'short_name' => 'HeliWind',
        'tagline' => 'Powering Tomorrow with Sun & Wind',
        'phone' => '+91 8544247902',
        'phone_raw' => '8544247902',
        'email' => 'support@heliwindenergy.com',
        'website' => 'www.heliwindenergy.com',
        'address' => [
            'head' => 'Corporate Office — HeliWind Energy Solution, India',
            'mfg' => 'Manufacturing & Warehouse Unit — HeliWind Energy Solution, India',
        ],
    ],
    'hero_slides' => [
        [
            'id' => 1,
            'kicker' => 'welcome to HeliWind Energy',
            'title' => 'Clean Energy Solutions for Homes & Businesses',
            'subtitle' => 'Solar EPC · Wind-hybrid systems · EV charging',
            'cta' => 'Know More',
            'image' => 'https://images.unsplash.com/photo-1761472823286-9f6093ed6663?crop=entropy&cs=srgb&fm=jpg&ixid=M3w3NDk1Nzl8MHwxfHNlYXJjaHwyfHxzb2xhciUyMHBhbmVscyUyMHJvb2Z0b3B8ZW58MHx8fHwxNzg0NTY4MTIwfDA&ixlib=rb-4.1.0&q=85',
        ],
        [
            'id' => 2,
            'kicker' => 'HeliWind Electric Charging',
            'title' => 'One Stop EV Charging Solution',
            'subtitle' => 'Powering the Future of Mobility',
            'cta' => 'Know More',
            'image' => 'https://images.unsplash.com/photo-1593941707874-ef25b8b4a92b?crop=entropy&cs=srgb&fm=jpg&ixid=M3w4NjA2MTJ8MHwxfHNlYXJjaHwxfHxFViUyMGNoYXJnaW5nJTIwc3RhdGlvbnxlbnwwfHx8fDE3ODQ1NjgxMjB8MA&ixlib=rb-4.1.0&q=85',
        ],
        [
            'id' => 3,
            'kicker' => 'Save Environment, Reduce Bills',
            'title' => 'Be a part of the Green Revolution',
            'subtitle' => 'Support renewable energy for a healthier planet',
            'cta' => 'Contact Us',
            'image' => 'https://images.pexels.com/photos/12224996/pexels-photo-12224996.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940',
        ],
        [
            'id' => 4,
            'kicker' => 'Become Our Business Partner',
            'title' => 'Grow with HeliWind Energy Solution',
            'subtitle' => 'Freelancer opportunities across India',
            'cta' => 'Join Us Today',
            'image' => 'https://images.pexels.com/photos/8783541/pexels-photo-8783541.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940',
        ],
    ],
    'nav_links' => [
        ['label' => 'Home', 'href' => '#home'],
        ['label' => 'About', 'href' => '#about'],
        ['label' => 'Services', 'href' => '#services'],
        ['label' => 'Freelancer', 'href' => '#freelancer'],
        ['label' => 'EV Charging', 'href' => '#ev'],
        ['label' => 'Projects', 'href' => '#projects'],
        ['label' => 'Contact', 'href' => '#contact'],
    ],
    'tabs' => [
        'vision' => [
            '50 MW capacity of installed projects',
            'Presence in international markets',
            'A strong project portfolio across sectors',
            'Healthy operating and finance metrics',
            'Major EV-charge supplies for last-mile connectivity',
            'R&D center integrating solar + storage for 24-hour energy',
        ],
        'plan' => [
            '2 GW of executed capacity',
            'Become a leading solar EPC company in India',
            'Expand into international markets',
            'Provide hostile-terrain EV station solutions',
            'Establish an in-house battery-technology manufacturing setup',
        ],
        'verticals' => [
            ['title' => 'SOLAR EPC & DEVELOPMENT', 'desc' => 'End-to-end solar engineering, procurement and construction for residential, commercial and industrial customers.'],
            ['title' => 'E-MOBILITY SOLUTIONS', 'desc' => 'AC & DC EV charging stations, site-planning and turnkey installation for fleets, malls and highways.'],
            ['title' => 'ENERGY STORAGE', 'desc' => 'Reliable battery-storage systems that pair with solar to deliver clean power around the clock.'],
        ],
        'awards' => [
            'ISO 9001:2015 Certified',
            'ISO 45001:2018 Certified',
            'ISO 14001:2015 Certified',
            'TUV-Rhineland Certified',
            'BIS Certified',
            'Make In India Certified',
        ],
    ],
    'freelancer_plans' => [
        [
            'name' => 'Starter Freelancer',
            'price' => '₹9,999',
            'tax' => '+GST',
            'features' => [
                'HeliWind starter kit & product catalog',
                'Digital marketing collaterals',
                'Online onboarding & training',
                'Government-subsidy assistance',
                'Dedicated relationship manager',
                'Project execution support',
                'Performance incentive up to ₹25,000',
            ],
            'highlight' => false,
        ],
        [
            'name' => 'Growth Freelancer',
            'price' => '₹24,999',
            'tax' => '+GST',
            'features' => [
                'Everything in Starter',
                'Full marketing support',
                'Advanced sales training',
                'Business-development guidance',
                'Local branding assistance',
                'Priority technical support',
                'Performance incentive up to ₹75,000',
            ],
            'highlight' => true,
        ],
        [
            'name' => 'Regional Freelancer',
            'price' => '₹49,999',
            'tax' => '+GST',
            'features' => [
                'Everything in Growth',
                'Regional expansion support',
                'Advanced business strategy',
                'Priority project coordination',
                'Premium branding assistance',
                'Dedicated senior manager',
                'Performance incentive up to ₹1,50,000',
            ],
            'highlight' => false,
        ],
        [
            'name' => 'Premium Freelancer',
            'price' => '₹99,999',
            'tax' => '+GST',
            'features' => [
                'Everything in Regional',
                'Premium+ marketing support',
                'Growth consultation calls',
                'Priority project handling',
                'Exclusive branding kit',
                'VIP freelancer support desk',
                'Performance incentive up to ₹3,00,000',
            ],
            'highlight' => false,
        ],
    ],
    'why_us' => [
        ['title' => 'Low Installation Costs', 'desc' => 'Cost-effective installation without compromising on quality — competitive pricing across every segment.'],
        ['title' => 'Reusable Energy', 'desc' => 'Eco-first practices — efficient recycling and responsible sourcing reduce our environmental footprint.'],
        ['title' => 'Healthy and Safe Energy', 'desc' => 'Products carefully engineered to deliver safe, harmless energy for your home and family.'],
        ['title' => 'Multi Purpose Usage', 'desc' => 'Flexible products for homes, businesses, street-lights and industrial installations across every segment.'],
        ['title' => 'Durable and Long Lasting', 'desc' => 'Tested, certified products that withstand weather and time — built for the long haul.'],
        ['title' => 'Hassle Free Installation', 'desc' => 'A skilled crew that handles surprises, so you enjoy a stress-free setup and worry-free service.'],
    ],
    'testimonials' => [
        ['name' => 'Mr. Rajesh Gupta', 'location' => 'Delhi', 'text' => 'A dynamic entrepreneur with decade-plus experience across sectors. His market reach and business acumen make him a valued HeliWind freelancer.'],
        ['name' => 'Mr. Saroj Tripathi', 'location' => 'Pune Raigad', 'text' => 'Runs multiple businesses and is well-known locally. Ready to accept challenges and grow across any field with HeliWind.'],
        ['name' => 'Mr. Ganesh Rupnar', 'location' => 'Beed / Parbhani', 'text' => 'With 6+ years of business experience, he added a new revenue stream by supporting green energy through HeliWind.'],
        ['name' => 'Mr. Swapan Chakrabarty', 'location' => 'Guwahati (Assam)', 'text' => 'After 30+ years in a well-known organisation, he chose to participate in solar business as a HeliWind freelancer post-retirement.'],
        ['name' => 'Mr. Joydev Roy', 'location' => 'Raipur / Durg (Chhattisgarh)', 'text' => 'A multi-talented professional managing his existing work with 100% dedication — solar is now a proud part of his portfolio.'],
        ['name' => 'Mr. Niranga Ram Patel', 'location' => 'Jalore / Jodhpur (Rajasthan)', 'text' => 'Already runs a gas-agency business; seeing solar growth, he began his renewable-energy journey with HeliWind.'],
    ],
    'stats' => [
        ['label' => 'MW Projects', 'value' => 65, 'suffix' => '+'],
        ['label' => 'Freelance Partners', 'value' => 250, 'suffix' => '+'],
        ['label' => 'International Branches', 'value' => 5, 'suffix' => ''],
        ['label' => 'Domestic Branches', 'value' => 40, 'suffix' => '+'],
    ],
    'certifications' => [
        'Ministry of New and Renewable Energy (MNRE)',
        'Environmental Management System (EMS)',
        'Make In India',
        'Central Vigilance Commission',
        'Ministry of MSME',
        'ISO Certified',
    ],
    'news_logos' => [
        'Hindustan Times', 'ANI News', 'The Print', 'Daily Hunt', 'Zee5', 'Latestly', 'EQ Mag Pro', 'India News Network', 'Gujarat Samachar'
    ],
];
